environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      RUNTIME_CONFIG: MT
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      RUNTIME_CONFIG: MD
    
build_script:
  - python build.py

artifacts:
  - path: output/protobuf_md_windows.zip
  - path: output/protobuf_mt_windows.zip

skip_commits:
  message: /.*\[skip appveyor\].*/
